### ISSUE TITLE
targetSdkVersion在30及以上：在自己的项目的manifest文件，按照谷歌要求注册需要使用的包名；

### ISSUE THREAD

**Issue by wangjiahui78** [MingJieZuo/SimpleLocation#2]
<queries>
        
        
        <package android:name="com.blog.service" />
    </queries>

<queries>
        
        
        <package android:name="com.blog" />
    </queries>

**Comment by mjzuo** [comment]
谢提醒，已修改。

**Comment by zuo26** [comment]
谢提醒，已修改。
